version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # You can choose the image you prefer
    steps:
      - checkout
      - run:
          name: Install PostgreSQL and dependencies from sudo_requirements.txt
          command: |
            # Make sure the file is in the repo
            cat sudo_requirements.txt | sudo bash
      - run:
          name: Install Python dependencies
          command: |
            pip install -r requirements.txt

workflows:
  version: 2
  build:
    jobs:
      - build
