version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout


      - name: Run the pgdg script to set up PostgreSQL repository
        shell: /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
        args:
          creates: /etc/apt/sources.list.d/pgdg.list

      - name: Install curl and ca-certificates
        apt:
          name:
            - curl
            - ca-certificates
          state: present

      - name: Install the postgresql key
        shell: curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
        args:
          creates: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc

      - name: Add PostgreSQL repository to sources.list
        shell: |
          echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
        args:
          creates: /etc/apt/sources.list.d/pgdg.list

      - name: Update apt cache
        apt:
          update_cache: yes

      - name: Install PostgreSQL
        apt:
          name: postgresql
          state: present
          install_recommends: yes




      - run:
          name: Checking the working directory
          command: "dir"
      - run:
          name: Verify Python Installation
          command: "python --version"
      - run:
          name: Ensure pip is installed
          command: "python -m ensurepip"
      - run:
          name: Upgrade pip
          command: "python -m pip install --upgrade pip"
      - run:
          name: Install dependencies
          command: "pip install -r requirements.txt"
     