version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Checking the working directory
          command: "dir"
      - run:
          name: Verify Python Installation
          command: "python --version"
      - run:
          name: Ensure pip is installed
          command: "python -m ensurepip"
      - run:
          name: Upgrade pip
          command: "python -m pip install --upgrade pip"
      - run:
          name: Install dependencies
          command: "pip install -r requirements.txt"
      - run:
          name: Run Scrapy Spider
          working_directory: three_websites/three_websites/spiders
          command: "python -m scrapy crawl financial_prices"

          
      - run:
          name: Connection to the database
          working_directory: three_websites/three_websites/spiders
          command: psql postgresql://erik_user:vJnjEibIrqr3BkvAwmjcZdbUiFi4oXfK@dpg-ctuh0f8gph6c73eqljrg-a.oregon-postgres.render.com/erik
      - run: 
          name: running sql queries
          command: \i post.sql

