version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
     
      - run:
          name: Connection to the database
          working_directory: three_websites/three_websites/spiders
          command: psql postgresql://postgres:BSwtGv4AvaKvoYJD@quarterly-prominent-seagull.data-1.use1.tembo.io:5432/postgres
      - run: 
          name: running sql queries
          command: \i post.sql