version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  install_postgresql:
    executor:
      name: win/windows-server-2019
    steps:
      - checkout
      - win/setup_remote_docker:
          version: "19.03.12"
          
      - run: 
          name: connect to database
          working_directory: three_websites/three_websites/sql
          command: |
              psql postgresql://postgres:BSwtGv4AvaKvoYJD@quarterly-prominent-seagull.data-1.use1.tembo.io:5432/postgres'
              # Inserting into the database
              \i insert.sql;

workflows:
  version: 2
  install_postgresql_workflow:
    jobs:
      - install_postgresql
