version: 2.1


jobs:
  build:
    docker:
      - image: cimg/python:3.10
      - image: cimg/postgres:14.10
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: testdb
          POSTGRES_PASSWORD: pass

    environment:
      DATABASE_URL: postgres://circleci:pass@localhost:5432/testdb

    steps:
      - checkout

      - run:
          name: Install dockerize
          command: |
            curl -sSL https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz | \
            sudo tar -xzv -C /usr/local/bin

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Wait for PostgreSQL to be ready
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 60s

      - run:
          name: Test DB connection using connection string
          command: |
            psql -4 "postgresql://postgres:tlotliso101@db.ltxefuhyxlyhezlvdned.supabase.co:5432/postgres" -c "SELECT version();"
            echo "hllo"
