version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10  # Your Python version
      - image: cimg/postgres:14.10
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: testdb
          POSTGRES_PASSWORD: pass

    environment:
      DATABASE_URL: postgres://circleci:pass@localhost:5432/testdb

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Wait for PostgreSQL to be ready
          command: |
            sudo apt-get update && sudo apt-get install -y postgresql-client
            dockerize -wait tcp://localhost:5432 -timeout 60s

      - run:
          name: Test DB connection using connection string
          command: |
            psql "$DATABASE_URL" -c "SELECT version();"

      - run:
          name: Run Python tests
          command: |
            pytest  # or your test runner



