



 version: 2.1

 orbs:
    node: circleci/node@7.1.0

 jobs:
    build:
      executor: node/default
 
      steps:
        - checkout
        - node/install-packages:
            pkg-manager: npm
     
        - run:
            command: npm run tests
            name: run tests
 
        - run: 
            command: bash sudo_requirements.txt
            name: download postgresql
        - run: 
            command: psql --version
            name: check psql version

      - run:
          name: enter spql teminal
          working_directory: three_websites/three_websites/sql
          command: |
              psql --version
        
