name: Python + Supabase DB Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client dnsutils

      - name: Resolve IPv4 of Supabase host (avoid IPv6 issues)
        run: |
          ./install_postgres.sh
          

      - name: Test DB connection
        working-directory: three_websites/three_websites/sql
        run: |
          echo "$DATABASE_URL"

          ls
          psql "$DATABASE_URL" -c "SELECT version();"

      - name : TLOTLISO
        run: |
          psql -version
        
          

    
