name: Python CI

on: [push]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Access secret in Python script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python scripts.py
