name: Python CI

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  # You can also trigger on other events, such as:
  # pull_request:
  #   branches:
  #     - main

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Access secret in Python script
        run: |
          cd three_websites/three_websites
          python scripts.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}